---
driver:
  name: ec2

transport:
  max_ssh_sessions: 6

# Ansible will be our provisioner
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false
  idempotency_test: true

verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

platforms:
  - name: amazon-2
  - name: amazon-1
  - name: centos-7
  - name: centos-6
  - name: rhel-7
  - name: rhel-6
  - name: debian-9
  - name: debian-8
  - name: debian-7
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04

# Define playbook to use
suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
