---
# tasks file for ansible-role-amazon-inspector

- name: Linux | Include OS specific variables.
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_system == "Linux"

- name: Windows | Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Windows"

- name: Install aws ssm agent
  include_tasks: "setup-{{ ansible_system }}.yml"
