---
# tasks file for ansible-role-amazon-inspector

- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install aws ssm agent
  include_tasks: "setup-{{ ansible_system }}.yml"