---
# Install aws inspector agent on Linux family system

- name: Linux | Install dependency
  package:
    name: "{{ inspector_dependencies_packages }}"
    state: present

- name: Linux | Download aws inspector agent
  get_url:
    url: "{{ inspector_url_download }}"
    dest: "{{ inspector_dest_path }}/awsagent"
    mode: 0755

- name: Linux | Install aws inspector agent
  command: "{{ inspector_dest_path }}/awsagent"
  args:
    creates: /opt/aws/awsagent/bin/awsagent

- name: Linux | Inspector service
  service:
    name: awsagent
    enabled: true
    state: started
