---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${distribution:-centos-7}
    image: diodonfrost/${distribution:-centos-7}-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
