---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: linux
    image: diodonfrost/${image:-ansible-centos:7}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
