name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  test:
    name: Ansible version ${{ matrix.ansible_version }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ansible_version:
          - ">=2.8.1,<2.9"
          - ">=2.7,<2.8"
          - ">=2.6,<2.7"
          - ">=2.5,<2.6"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Test Ansible role Logrotate
        run: |
          python -m pip install ansible"${{ matrix.ansible_version }}" ansible-lint
          ansible --version
          ansible-lint ./
