name: CI

on:
  push:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - centos-8
          - centos-7
          - fedora-29
          - fedora-28
          - fedora-27
          - fedora-26
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - ubuntu-14.04
          - debian-10
          - debian-9
          - debian-8
          - oraclelinux-7
          - amazonlinux-2
          - amazonlinux-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.51

      - name: Test Ansible role amazon-inspector
        run: |
          container_id=$(mktemp)

          # Run container and mount ansible role with it
          sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-amazon-inspector:ro diodonfrost/${{ matrix.distribution }}-ansible:latest > "${container_id}"

          # Check syntax
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-inspector/tests/test.yml --syntax-check

          # Run ansible playbook
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-inspector/tests/test.yml -e "test_mode=true"

          # Test indempotence
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-inspector/tests/test.yml -e "test_mode=true" \
          | grep -q 'changed=0.*failed=0' \
          && (echo 'Idempotence test: pass' && exit 0) \
          || (echo 'Idempotence test: fail' && exit 1)

          # Test role
          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
